### PR TITLE
Implement load and save file in the ui

### PR DESCRIPTION
**Pull request by GaelleMarais**

### CODE REVIEW

**Comment by GaelleMarais** [comment]
@Kagamihime  Can you help me understand why I have a memory leak even if I have freed the variable path plz ?

**Comment by Kagamihime** [comment]
I don't know why but you must check that path is not NULL after calling malloc

**Comment by Kagamihime** [comment]
Check out this http://cppcheck.sourceforge.net/forum/viewtopic.php?f=4&t=50

**Comment by GaelleMarais** [comment]
Thank you very much for your help but there is still the same error :(

**Comment by GaelleMarais** [comment]
Thank you very much for your help but there is still the same error :(

**Comment by GaelleMarais** [comment]
Thank you !!! 
Just need to rebase now

**Comment by Kagamihime** [comment]
Great !! I was afraid it was going to be something obscure but it's okay :)

**Pull request merged**
