### PR TITLE
Add project's skeleton

### PR DESCRIPTION
**Pull request by GaelleMarais**
The skeleton contains all the files that will be needed for the project.
The modules contains all the prototypes of the functions that will be needed.
The Makefile allows to compile all the files using "$make all"

Closes https://github.com/Kagamihime/VIlain/issues/7

### CODE REVIEW

**Comment by Kagamihime** [comment]
Please, split you commits so that there is a commit for each module and the Makefile (each commit must remain atomic)

**Comment by GaelleMarais** [comment]
Done

**Comment by Kagamihime** [comment]
You need to use `git rebase -i master` in order to delete the first two commits of your branch, then push to your branch with `git push --force`.

Also, you have to change your e-mail your in your git config (with git config --global) so that it matches the e-mail of your GitHub account and modify your commits accordingly, please

**Comment by GaelleMarais** [comment]
It's done :)

**Pull request merged**
