### PR TITLE
VIlain_UML_version_1.dia: Add the project's UML

### PR DESCRIPTION
**Pull request by DavidVn64**
First shot of the UML design.

Closes https://github.com/Kagamihime/VIlain/issues/2

### CODE REVIEW

**Comment by Kagamihime** [comment]
There are several things that should be modified:

1. It is useless to specify `.c` and `.h` as doing this diagram is only about designing the API: there should be just one frame mentioning the struct and the functions available outside the module for each module.
2. You should rename the modules' names using `snake_case` instead of `CamelCase`.
3. You should write `char **` instead of `char*[]` (although I know that both can be used), it's clearer about what the variable will be.
4. We are not doing POO so every functions on structs should have as their first argument, a pointer to the struct they are manipulating (like `void init(BUFFER *buff)` for example).

**Comment by Kagamihime** [comment]
Note that if you want to modify your latest commit (its message or the modifications it does), do your modifications and then run `git commit -a --amend` (don't edit your commit message unless it's what you want to do) on your branch ;)

**Comment by DavidVnGit** [comment]
Alright, thank you for the advices. I just reviewed the previous UML and pushed the new one. Please check it out.

**Comment by Kagamihime** [comment]
Nice job!

**Pull request merged**
